apps += Rpi::App
app_headers += apps/rpi/app.h

app_objs += $(addprefix apps/rpi/,\
  app.o\
	rpi_controller.o\
	rpi_view.o\
)

app_images += apps/rpi/rpi_icon.png

i18n_files += $(addprefix apps/rpi/,\
	base.de.i18n\
	base.en.i18n\
	base.es.i18n\
	base.fr.i18n\
	base.pt.i18n\
)
